import './globals.css'
import { Rubik } from 'next/font/google'

// this is how we create fonts - they are self-hosted
const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Ticket Dashboard',
  description: 'Generated by create next app',
}

// When wrapping a folder name in /app folder with (), it tells next.js that it's a folder for 
// grouping pages together. So it won't be included in the url path.

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        
        {children}
      </body>
    </html>
  )
}
